WITH epi AS 
(
SELECT DISTINCT 
 IDEN.IDENTITY_ID
, TO_CHAR(HT.SERVICE_DATE, 'MM/DD/YYYY') AS PROC_DATE
, HT.CPT_CODE AS CPT
, ser.prov_name as prov_name
, HT.Pat_enc_CSN_ID
/*, EDG.DX_NAME
, EDG.CURRENT_ICD10_LIST*/

FROM 
CLARITY.HSP_ACCOUNT HA
INNER JOIN CLARITY.HSP_TRANSACTIONS HT ON HA.HSP_ACCOUNT_ID=HT.HSP_ACCOUNT_ID
INNER JOIN CLARITY.CLARITY_SER SER ON  HT.BILLING_PROV_ID=SER.PROV_ID
INNER JOIN CLARITY.IDENTITY_ID IDEN ON HA.PAT_ID=IDEN.PAT_ID
INNER JOIN CLARITY.PATIENT PAT ON HA.PAT_ID=PAT.PAT_ID
LEFT JOIN CLARITY.CLARITY_DEP DEP ON HA.DISCH_DEPT_ID = DEP.DEPARTMENT_ID
LEFT JOIN CLARITY_LOC LOC ON DEP.REV_LOC_ID = LOC.LOC_ID
/*INNER JOIN CLARITY.HSP_ACCT_DX_LIST HA_DX ON HA.HSP_ACCOUNT_ID = HA_DX.HSP_ACCOUNT_ID
INNER JOIN CLARITY.CLARITY_EDG EDG ON HA_DX.DX_ID = EDG.DX_ID*/

WHERE 
HT.SERVICE_DATE >= TO_DATE('01/04/2019', 'MM/DD/YYYY') AND HT.SERVICE_DATE <= TO_DATE('01/04/2019', 'MM/DD/YYYY')--BETWEEN  to_date('06/30/2017', 'MM/DD/YYYY') AND to_date('12/31/2017', 'MM/DD/YYYY')
AND HT.TX_TYPE_HA_C=1 
AND IDEN.IDENTITY_TYPE_ID=154 
AND HA.ACCT_BILLSTS_HA_C <> 99
AND LOC.HOSP_PARENT_LOC_ID = 1010
AND HT.CPT_CODE LIKE '934%'

UNION 
SELECT DISTINCT 
IDEN.IDENTITY_ID
, TO_CHAR(ARPB.SERVICE_DATE, 'MM/DD/YYYY') AS PROC_DATE
, ARPB.CPT_CODE AS CPT
, ser.prov_name as prov_name
, HT.Pat_enc_CSN_ID
/*, EDG.DX_NAME
, EDG.CURRENT_ICD10_LIST*/


FROM CLARITY.ARPB_TRANSACTIONS ARPB
INNER JOIN CLARITY.IDENTITY_ID IDEN ON ARPB.PATIENT_ID = IDEN.PAT_ID
INNER JOIN CLARITY.PATIENT PAT ON ARPB.PATIENT_ID = PAT.PAT_ID
INNER JOIN CLARITY.CLARITY_SER SER ON ARPB.BILLING_PROV_ID = SER.PROV_ID
/*INNER JOIN V_ARPB_CODING_DX ARPB_DX ON ARPB.TX_ID = ARPB_DX.TX_ID
INNER JOIN CLARITY_EDG EDG ON ARPB_DX.DX_ID = EDG.DX_ID*/
INNER JOIN CLARITY.CLARITY_TDL_TRAN TDL ON ARPB.TX_ID = TDL.TX_ID
LEFT JOIN CLARITY.HSP_ACCOUNT HA ON TDL.HSP_ACCOUNT_ID = HA.HSP_ACCOUNT_ID

INNER JOIN CLARITY.HSP_TRANSACTIONS HT ON HA.HSP_ACCOUNT_ID=HT.HSP_ACCOUNT_ID


LEFT JOIN CLARITY.CLARITY_DEP DEP ON HA.DISCH_DEPT_ID = DEP.DEPARTMENT_ID
left JOIN CLARITY.CLARITY_LOC LOC ON DEP.REV_LOC_ID = LOC.LOC_ID

WHERE ARPB.SERVICE_DATE >= TO_DATE('01/04/2019', 'MM/DD/YYYY') AND ARPB.SERVICE_DATE <= TO_DATE('01/04/2019', 'MM/DD/YYYY') -- BETWEEN to_date('06/30/2017', 'MM/DD/YYYY') AND to_date('12/31/2017', 'MM/DD/YYYY')
AND ARPB.TX_TYPE_C=1
AND IDEN.IDENTITY_TYPE_ID = 154
AND LOC.HOSP_PARENT_LOC_ID = 1010
AND ARPB.CPT_CODE LIKE '934%'
)

select distinct * from epi order by identity_id, proc_date